services:

  redis:
    image: redis:7.2
    restart: always
    hostname: redis
    networks:
      - stroymag_common

  rabbitmq:
    image: rabbitmq:3.7-management
    restart: always
    hostname: rabbitmq
    ports:
      - "8082:15672"
    networks:
      - stroymag_common
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    env_file:
      - path: ./.env
        required: true

  mysql:
    image: mysql:8.3
    restart: always
    hostname: mysql
    command: ["mysqld", "--authentication_policy=mysql_native_password"]
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "8081:3306"
    networks:
      - stroymag_common
    env_file:
      - path: ./.env
        required: true



networks:
  stroymag_common:
    driver: bridge
